### PR TITLE
Add pi user home directory, and install sudo.

### PR DESCRIPTION
**Pull request by ounis**
I need this because I run some scripts on a CI server, those scripts use the pi home folder and sudo, and I don't need to add too much conditions in my scripts to check whether I run them on a real device or on CI.

### CODE REVIEW

**Comment by ounis** [comment]
I don't understand why Travis tests failed.

**Comment by jedahan** [comment]
It would be nice if this PR only added sudo...though doesn't docker run as root anyway?

**Comment by ounis** [comment]
> It would be nice if this PR only added sudo...though doesn't docker run as root anyway?

You're right I got carried out adding more stuff.
I'm reverting the other stuff.

**Comment by ounis** [comment]
> It would be nice if this PR only added sudo...though doesn't docker run as root anyway?

And about root, you're right, but the scripts I'm running are failing because they use sudo and can't find it.

**Comment by jedahan** [comment]
Ahh
One workaround, if you are only using sudo for root permissions and not passing any flags, is (zsh syntax):
```zsh
(( $+commands[sudo] )) || sudo() { $* }
```

Either way, thanks for updating the PR!

**Comment by ryankurte** [comment]
thanks for the pr! seems like a reasonable addition to me, CI seems a bit toasted for [unrelated reasons](https://travis-ci.org/ryankurte/docker-rpi-emu/builds/521055599#L1994) so i'll just merge here.

**Comment by ounis** [comment]
> Ahh
> One workaround, if you are only using sudo for root permissions and not passing any flags, is (zsh syntax):
> 
> ```shell
> (( $+commands[sudo] )) || sudo() { $* }
> ```
> 
> Either way, thanks for updating the PR!

Thx for the hint, I don't think I'll use it now since the PR was merged, but it can be useful later :)

**Pull request merged**
